Repository chaotic-cx/nyx, pull requests merged in 2023-05, with the labels that each got.

#64 flake: track nixos-unstable
  flake.lock
  flake.nix
Labels: cached

#65 flake-20230501-1; proton-ge-custom: 7-55 -> 8-1
  flake.lock
  pkgs/mesa-git/default.nix
  pkgs/proton-ge-custom/default.nix
  shared/utils.nix
Labels: cached, high-priority

#68 sway_git: remove already merged patch
  overlays/default.nix
  pkgs/sway-unwrapped-git/default.nix
  shared/utils.nix
Labels: cached, bug

#67 firedragon: version 112.0.2
  pkgs/firedragon/src.json
Labels: needs-cache

#74 flake-20230503-1: mesa, sway, wlroots, yuzu-ea
  flake.lock
Labels: high-priority, maintainer-building-cache

#75 ci: use nixpkgs/nix-flakes instead of nixos/nix
  .circleci/config.yml
Labels: enhancement

#76 linux-cachyos: 6.3.1, built with linuxManualConfig
  pkgs/linux-cachyos/default.nix
Labels: needs-cache

#77 proton-ge-custom: allow some easy overrides
  pkgs/proton-ge-custom/default.nix
Labels: enhancement

#79 dr460nized-kde-theme: add skel directory in preparation for garuda flake
  pkgs/dr460nized-kde-theme/default.nix
Labels: cached

#81 flake-20230504-1: mesa_git, sway_git, wlroots_git, yuzu-ea_git
  flake.lock
  pkgs/linux-cachyos/default.nix
Labels: cached, high-priority

#83 flake-20230505-1; bump nixpkgs; fix mesa_git
  flake.lock
  pkgs/mesa-git/default.nix
Labels: cached, high-priority

#85 flake-20230506-1; proton-ge-custom: 8.1 -> 8.2
  flake.lock
  pkgs/proton-ge-custom/default.nix
Labels: cached, high-priority

#87 flake-20230507-1: nixpkgs, mangohud_git, mesa_git, wlroots_git, yuzu-ea_git
  flake.lock
Labels: cached, high-priority

#90 latencyflex-vulkan: init at unstable-2023-04-16
  README.md
  overlays/default.nix
  pkgs/latencyflex-vulkan/default.nix
Labels: cached

#89 modules/gamescope: add session.steamArgs
  README.md
  modules/gamescope.nix
Labels: cached

#91 flake-20230508-1: input-leap, mangohud, mesa, wlroots, yuzu
  flake.lock
Labels: high-priority

#92 README: separate module from configuration
  README.md
Labels: enhancement

#93 flake-20230509-1: mesa_git, sway_git, yuzu-ea_git
  flake.lock
Labels: cached, high-priority

#94 flake-20230510-1: gamescope, mangohud, mesa, sway, swaylock-plugin, yuzu-ea
  flake.lock
Labels: high-priority, maintainer-building-cache

#95 gamescope_git: update buildInputs
  pkgs/gamescope-git/default.nix
Labels: cached, high-priority, bug

#96 flake-20230511-1; proton-ge-custom: 8.2 -> 8.3
  flake.lock
  pkgs/proton-ge-custom/default.nix
Labels: cached, high-priority

#97 linux-cachyos: update 6.3.2
  pkgs/linux-cachyos/default.nix
Labels: cached

#100 flake-20230512-1: gamescope, mesa, wlroots, yuzu-ea
  flake.lock
Labels: cached, high-priority

#101 flake-20230513-1: gamescope, mesa, yuzu-ea
  flake.lock
Labels: high-priority, maintainer-building-cache

#102 builder: output new-failures.nix; add keep-alive; skip known failures
  devshells/builder.nix
  devshells/eval.nix
  devshells/failures.nix
Labels: enhancement

#99 linux_cachyos: re-add structuredExtraConfig (the sad way)
  devshells/failures.nix
  overlays/default.nix
  pkgs/linux-cachyos/default.nix
Labels: cached, bug

#103 linux_cachyos: fix structuredExtraConfig
  pkgs/linux-cachyos/default.nix
Labels: cached, bug

#104 linux_cachyos: try generating a configfile
  devshells/failures.nix
  pkgs/linux-cachyos/default.nix
Labels: cached, bug

#106 flake-20230515-1: input-leap, mesa, wlroots, yuzu-ea
  devshells/builder.nix
  devshells/failures.nix
  flake.lock
  overlays/default.nix
  pkgs/yuzu-ea-git/default.nix
Labels: cached, high-priority

#108 modules/mesa-git: fix purity by recreating opengl-drivers' env and using LD_LIBRARY_PATH
  README.md
  modules/mesa-git.nix
Labels: enhancement

#109 flake-20230516-1: gamescope, mangohud, mesa, nixpkgs, yuzu-ea
  devshells/failures.nix
  flake.lock
Labels: cached, high-priority

#113 flake-20230518-1: mesa, wlroots, yuzu-ea
  flake.lock
Labels: cached, high-priority

#115 beautyline-icons: update to unstable-2023-05-18
  pkgs/beautyline-icons/default.nix
Labels: cached

#114 dr460nized-kde-theme: update to unstable-2023-05-18
  pkgs/dr460nized-kde-theme/default.nix
Labels: cached

#116 flake-20230518-2: mesa, nixpkgs
  devshells/failures.nix
  flake.lock
Labels: cached, high-priority

#107 linux_cachyos: 6.3.2-1 -> 6.3.3-1
  devshells/failures.nix
  overlays/default.nix
  pkgs/linux-cachyos/default.nix
  pkgs/linux-cachyos/versions.nix
Labels: enhancement, cached

#117 openmohaa: init
  README.md
  overlays/default.nix
  pkgs/openmohaa/default.nix
Labels: cached

#118 flakes-20230520-1; openmohaa bump; more docs; templates; CODEOWNERS
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/new-package-requests.yml
  .github/ISSUE_TEMPLATE/reporting-bugs.yml
  .github/ISSUE_TEMPLATE/reporting-outdated-packages.yml
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  devshells/failures.nix
  flake.lock
Labels: enhancement, cached, high-priority

#119 flake-20230521-1:mesa, sway, yuzu
  flake.lock
Labels: cached, high-priority

#120 openmohaa: 0.50 -> 0.52.0
  devshells/failures.nix
  pkgs/openmohaa/default.nix
Labels: cached

#121 flake-20230522-2: mangohud, mesa, nixpkgs, wlroots, yuzu-ea
  devshells/failures.nix
  flake.lock
Labels: cached, high-priority

#122 openmohaa: 0.52.0 -> 0.53.2
  pkgs/openmohaa/default.nix
Labels: cached

#124 flake-20230524-1: input-leap, mesa, nixpkgs, wlroots, yuzu-ea
  flake.lock
Labels: cached, high-priority

#125 firedragon: update 113.0.2
  pkgs/firedragon/src.json
Labels: cached, high-priority

#126 flake-20230525-1: mangohud, mesa, nixpkgs, yuzu-ea
  flake.lock
Labels: cached, high-priority

#127 libei: 1.0.0rc1 -> 1.0.0rc2; linux_cachyos: 6.3.3 -> 6.3.4
  devshells/failures.nix
  pkgs/libei/default.nix
  pkgs/linux-cachyos/versions.nix
Labels: cached

#130 flake-20230527-1: gamescope, mesa, wlroots, yuzu
  flake.lock
  overlays/default.nix
Labels: cached, high-priority

#131 bump-20230528-1; README: move cache and update
  README.md
  flake.lock
Labels: cached, high-priority

#134 flake-20230531-1 + openmohaa
  devshells/failures.nix
  flake.lock
  pkgs/openmohaa/default.nix
Labels: cached, high-priority
