Repository chaotic-cx/nyx, pull requests merged in 2023-07, with the labels that each got.

#185 linux-cachyos: add updateScript; 6.4 -> 6.4.1
  devshells/failures.nix
  overlays/default.nix
  pkgs/linux-cachyos/default.nix
  pkgs/linux-cachyos/update.nix
  pkgs/linux-cachyos/versions.json
  pkgs/linux-cachyos/versions.nix
Labels: maintainer-building-cache

#186 flake-20230701-1: mesa, wlroots, yuzu-ea
  flake.lock
Labels: maintainer-building-cache

#188 flake-20230702-1: mesa, wlroots, yuzu-ea
  flake.lock
Labels: maintainer-building-cache

#189 Bump/20230703-1
  flake.lock
  pkgs/proton-ge-custom/versions.json
Labels: high-priority

#191 flake-20230704-1: mesa, yuzu-ea
  flake.lock
Labels: cached

#192 flake-20230705-1: mesa, wlroots, yuzu-ea
  flake.lock
Labels: maintainer-building-cache

#193 linux_cachyos: 6.4.1 -> 6.4.2; flake-20230705-2
  devshells/failures.nix
  flake.lock
  pkgs/linux-cachyos/versions.json
Labels: high-priority, maintainer-building-cache

#195 blurredwallpaper: init at v2.2
  overlays/default.nix
  pkgs/beautyline-icons/default.nix
  pkgs/blurredwallpaper/default.nix
  pkgs/dr460nized-kde-theme/default.nix
  pkgs/fastfetch/default.nix
Labels: needs-cache

#198 Enhanceblurred
  pkgs/blurredwallpaper/default.nix
Labels: cached

#197 nordvpn: init at 3.16.3
  modules/nordvpn.nix
  overlays/default.nix
  pkgs/nordvpn/default.nix
Labels: cached

#200 dr460nized-kde-theme: remove invalid launchers; update; add buildinput
  pkgs/dr460nized-kde-theme/default.nix
Labels: cached

#202 linux_hdr: rebase on linux_cachyos
  devshells/failures.nix
  overlays/default.nix
  pkgs/linux-cachyos/default.nix
  pkgs/linux-cachyos/versions.json
  pkgs/linux-hdr/default.nix
Labels: enhancement, maintainer-building-cache

#207 devshells/document: init
  devshells/builder.nix
  devshells/bumper/update-scripts.nix
  devshells/comparer.nix
  devshells/default.nix
  devshells/document.nix
  devshells/eval.nix
  flake.nix
  modules/steam-compat-tools.nix
  overlays/default.nix
  pkgs/wlroots-git/default.nix
  shared/recursion-helper.nix
Labels: wip

#208 flake-20230715-1: mangohud, mesa, sway, wlroots
  devshells/failures.nix
  flake.lock
Labels: cached, high-priority

#210 flake-20230716-1: mesa, wlroots
  .github/ISSUE_TEMPLATE/new-package-requests.yml
  LICENSE
  devshells/document.nix
  devshells/failures.nix
  flake.lock
Labels: high-priority, maintainer-building-cache

#213 Bump 20230719-1
  .github/workflows/build.yml
  .github/workflows/document.yml
  .github/workflows/full-bump.yml
  devshells/bumper/default.nix
  devshells/failures.nix
  flake.lock
  modules/linux_hdr.nix
  overlays/default.nix
  pkgs/linux-cachyos/default.nix
  pkgs/linux-cachyos/versions.json
Labels: enhancement, high-priority, maintainer-building-cache

#215 yt-dlp_git: init
  flake.lock
  flake.nix
  overlays/default.nix
  pkgs/yt-dlp-git/default.nix
Labels: cached

#229 dr460nized-kde-theme: update to unstable-2023-07-29
  pkgs/dr460nized-kde-theme/default.nix
Labels: cached
