Repository chaotic-cx/nyx, pull requests merged in 2023-08, with the labels that each got.

#235 mesa_git: bump 20230801-2
  flake.lock
Labels: high-priority, maintainer-building-cache, bug

#240 Overall enhancements
  README.md
  devshells/document.nix
  flake.nix
  modules/common/nyx-cache.nix
  modules/common/nyx-overlay.nix
  modules/home-manager/default.nix
  modules/nixos/appmenu-gtk3-module.nix
  modules/nixos/default.nix
  modules/nixos/linux_hdr.nix
  modules/nixos/mesa-git.nix
  modules/nixos/nordvpn.nix
  modules/nixos/steam-compat-tools.nix
  modules/nixos/zfs-impermanence-on-shutdown.nix
  statix.toml
Labels: enhancement

#245 firedragon: update 116.0.1
  pkgs/firedragon/src.json
Labels: cached

#258 Bump/20230813 1
  flake.lock
  pkgs/firedragon/src.json
Labels: cached

#271 flake-20230819-2: mesa, yuzu-ea
  flake.lock
Labels: maintainer-building-cache

#273 ananicy-cpp-rules, beautyline-icons, dr460nized-kde-theme: add updater; nordvpn: update 3.16.5
  flake.lock
  flake.nix
  overlays/default.nix
  pkgs/ananicy-cpp-rules/default.nix
  pkgs/beautyline-icons/default.nix
  pkgs/dr460nized-kde-theme/default.nix
  pkgs/nordvpn/default.nix
Labels: cached

#292 nixos/mesa-git: add DM env; add half-baked virgl-based VM nixosTest
  .gitignore
  modules/nixos/mesa-git.nix
  pkgs/mesa-git/default.nix
  pkgs/mesa-git/test.nix
Labels: maintainer-building-cache
