Repository chaotic-cx/nyx, pull requests merged in 2023-06, with the labels that each got.

#136 flake-20230602-1: mass rebuild
  devshells/failures.nix
  flake.lock
  pkgs/mangohud-git/preload-nix-workaround.patch
Labels: high-priority, maintainer-building-cache, massive-rebuild

#137 beautyline-icons: update to unstable-2023-06-03
  pkgs/beautyline-icons/default.nix
Labels: cached

#138 modules/nyx-{cache,overlay}: init
  README.md
  modules/default.nix
  modules/nyx-cache.nix
  modules/nyx-overlay.nix
Labels: enhancement, high-priority

#139 flake-20230604-1: mesa, nixpkgs, sway, wlroots, yuzu-ea
  README.md
  devshells/failures.nix
  flake.lock
  overlays/default.nix
  pkgs/mesa-git/default.nix
  pkgs/sway-unwrapped-git/default.nix
  pkgs/wlroots-git/default.nix
Labels: maintainer-building-cache

#141 nyx-overlay: fix wrong definition of callPackage
  flake.nix
  modules/nyx-overlay.nix
Labels: high-priority, bug

#145 flake-20230605-1 + linux_cachyos
  devshells/failures.nix
  flake.lock
  pkgs/linux-cachyos/versions.nix
Labels: high-priority, maintainer-building-cache

#147 flake-20230606-1 + proton-ge-custom - libei
  README.md
  flake.lock
  overlays/default.nix
  pkgs/input-leap-git/default.nix
  pkgs/libei/default.nix
  pkgs/proton-ge-custom/default.nix
Labels: maintainer-building-cache

#149 flake-20230607-1: gamscope, mesa, sway, wlroots, yuzu-ea
  flake.lock
Labels: maintainer-building-cache

#154 flake-20230608-1: mangohud, mesa, wlroots, yuzu
  flake.lock
Labels: cached

#157 fastfetch: update to unstable-2023-06-10
  pkgs/fastfetch/default.nix
Labels: cached

#156 river: fetching submodules directly into flake.nix
  flake.lock
  flake.nix
  pkgs/river-git/default.nix
  pkgs/river-git/src.json
  pkgs/river-git/update.sh
Labels: cached

#158 flake.lock: bump {mangohud-git,mesa-git,yuzu-git}
  flake.lock
Labels: cached

#160 linux-cachyos: update 6.3.7; failures.nix: update
  devshells/failures.nix
  pkgs/linux-cachyos/default.nix
  pkgs/linux-cachyos/versions.nix
Labels: cached

#161 firedragon: update 114.0.1
  pkgs/firedragon/firedragon.nix
  pkgs/firedragon/src.json
Labels: cached

#165 flake-20230615-1: mangohud, mesa, wlroots, yuzu-ea
  flake.lock
Labels: cached

#164 linux-cachyos: update 6.3.8
  devshells/failures.nix
  pkgs/linux-cachyos/versions.nix
Labels: maintainer-building-cache

#166 flake-20230616-1: mesa, nixpkgs, wlroots, yuzu-ea
  flake.lock
Labels: high-priority, maintainer-building-cache

#172 flake-20230623-1: gamescope, mangohud, mesa, sway, wlroots, yuzu-ea
  devshells/failures.nix
  flake.lock
Labels: cached, high-priority

#173 linux_cachyos: 6.3.8 -> 6.3.9
  devshells/failures.nix
  pkgs/linux-cachyos/versions.nix
Labels: cached

#174 flake-20230625-1: mangohud, mesa, sway, wlroots, yuzu-ea
  flake.lock
Labels: cached

#175 openmohaa: 0.55.1 -> 0.55.2
  pkgs/openmohaa/default.nix
Labels: cached

#176 flake-20230626-1: mangohud, mesa, sway
  flake.lock
  modules/mesa-git.nix
Labels: cached

#179 linux_cachyos: 6.3.9-> 6.4
  README.md
  devshells/failures.nix
  pkgs/linux-cachyos/versions.nix
Labels: maintainer-building-cache

#180 flake-20230627-1: mesa, nixpkgs, sway, wlroots
  devshells/failures.nix
  flake.lock
  pkgs/sway-unwrapped-git/default.nix
Labels: high-priority, maintainer-building-cache

#181 bumper: init
  devshells/bumper/default.nix
  devshells/bumper/update-scripts.nix
  devshells/default.nix
  devshells/derivation-recursive-finder.nix
  overlays/default.nix
  pkgs/firedragon/update.nix
  pkgs/mangohud-git/default.nix
  pkgs/yuzu-ea-git/default.nix
Labels: enhancement

#183 dr460nized-kde-theme: update to unstable-2023-06-29
  pkgs/dr460nized-kde-theme/default.nix
Labels: cached
